collections:
  - name: courses
    label: Courses
    folder: data/courses.json
    create: true
    fields:
      - name: id
        label: ID
        widget: number
      - name: title_en
        label: Title (EN)
        widget: string
      - name: title_ar
        label: Title (AR)
        widget: string
      - name: price
        label: Price
        widget: number
      - name: image
        label: Image
        widget: image